# Site settings
title: CTFEDs.org
description: > # this means to ignore newlines until "baseurl:"
  Making the web better, one site at a time.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://ctfeds.org" # the base hostname & protocol for your site
# Build settings
markdown: kramdown
permalink: :title/

navigation:
 - title: Home
   url: /index.html
 - title: Call for speakers
   url: /call-for-speakers/
 - title: Front-end Fridays
   url: /front-end-fridays/index.html
 - title: Workshops
   url: /workshops/index.html
 - title: Organisers
   url: /organisers/
 - title: Sponsors
   url: /sponsors/index.html

exclude: [
    'node_modules',
    'bower_components',
    'Gruntfile.js',
    'package.json',
    'bower.json',
    'requirements.txt',
    'Gemfile',
    'Gemfile.lock',
    'README.md',
    'sass',
    'js',
    'coffee',
    'env',
    'tmp'
]